// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserInfo _$UserInfoFromJson(Map<String, dynamic> json) => UserInfo(
      id: (json['id'] as num?)?.toInt() ?? 0,
      uid: (json['uid'] as num?)?.toInt() ?? 0,
      name: json['name'] as String? ?? '',
      email: json['email'] as String? ?? '',
      phone: json['phone'] as String? ?? '',
      emailVerifiedAt: json['email_verified_at'] as String?,
      profileImg: json['profile_img'] as String?,
      coverImg: json['cover_img'] as String?,
      username: json['username'] as String?,
      nickname: json['nickname'] as String?,
      googleId: json['google_id'] as String?,
      appleId: json['apple_id'] as String?,
      refCode: json['ref_code'] as String?,
      userRef: json['user_ref'] as String?,
      bio: json['bio'] as String?,
      dob: json['dob'] as String?,
      badge: json['badge'] as String?,
      gender: json['gender'] as String?,
      label: json['label'] as String?,
      lifePathNum: json['life_path_num'] as String?,
      personality: json['personality'] as String?,
      webUrl: json['web_url'] as String?,
      twitterUrl: json['twitter_url'] as String?,
      linkedinUrl: json['linkedin_url'] as String?,
      fbUrl: json['fb_url'] as String?,
      igUrl: json['ig_url'] as String?,
      lastLoginDate: json['last_login_date'] as String?,
      kyc: json['kyc'] as String?,
      badges: json['badges'] as List<dynamic>?,
      status: json['status'] as String?,
      following: (json['following'] as num?)?.toInt(),
      follower: (json['follower'] as num?)?.toInt(),
      followedByUser: json['followed_by_user'] as bool?,
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      level: (json['level'] as num?)?.toInt(),
      levelImg: json['level_img'] as String?,
      interests: json['interests'] as List<dynamic>?,
    );

Map<String, dynamic> _$UserInfoToJson(UserInfo instance) => <String, dynamic>{
      'id': instance.id,
      'uid': instance.uid,
      'name': instance.name,
      'email': instance.email,
      'phone': instance.phone,
      'email_verified_at': instance.emailVerifiedAt,
      'profile_img': instance.profileImg,
      'cover_img': instance.coverImg,
      'username': instance.username,
      'nickname': instance.nickname,
      'google_id': instance.googleId,
      'apple_id': instance.appleId,
      'ref_code': instance.refCode,
      'user_ref': instance.userRef,
      'bio': instance.bio,
      'dob': instance.dob,
      'badge': instance.badge,
      'gender': instance.gender,
      'label': instance.label,
      'life_path_num': instance.lifePathNum,
      'personality': instance.personality,
      'web_url': instance.webUrl,
      'twitter_url': instance.twitterUrl,
      'linkedin_url': instance.linkedinUrl,
      'fb_url': instance.fbUrl,
      'ig_url': instance.igUrl,
      'last_login_date': instance.lastLoginDate,
      'kyc': instance.kyc,
      'badges': instance.badges,
      'status': instance.status,
      'following': instance.following,
      'follower': instance.follower,
      'followed_by_user': instance.followedByUser,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'level': instance.level,
      'level_img': instance.levelImg,
      'interests': instance.interests,
    };
